# --- !Ups
DROP TRIGGER IF EXISTS user_AFTER_DELETE;

CREATE DEFINER = CURRENT_USER TRIGGER user_AFTER_DELETE AFTER DELETE ON user FOR EACH ROW
BEGIN
  INSERT INTO omega.user_event(type, content) VALUES ('DELETE_USER', OLD.id);
END;

# --- !Downs
DROP TRIGGER IF EXISTS user_AFTER_DELETE$$
